stages:
  - build
  - deploy
  - cleanup

variables:
  BUILDING_BLOCK_REPO_URL: "gitlab.bsla.dev/microservice/dotnet/building-block.git"
  BUILDING_BLOCK_BRANCH: "stage"
  BUILDING_BLOCK_FOLDER: "building-block"

  PROJECT_NAME: "catalog-service"
  IMAGE_NAME: "img-catalog-service"
  CONTAINER_NAME: "cnt-catalog-service"
  IMAGE_TAG: "stage"
  BACKUP_SUFFIX: "-old"

  PORT_NUM_DOCKER: 44381
  PORT_NUM_EXPOSED: 44381
  ENVIRONMENT: "Production"

.build-template:
  stage: build
  script:
    - |
      set -e

      echo "@@@@@@@@@@@@@@ Preparing BuildingBlock Repo Started at: $(date '+%X') @@@@@@@@@@@@@@"

      if [ -d "../${BUILDING_BLOCK_FOLDER}" ]; then
        rm -rf "../${BUILDING_BLOCK_FOLDER}"
      fi

      git clone --depth 1 \
        -b "${BUILDING_BLOCK_BRANCH}" \
        "https://${BUILDING_BLOCK_USERNAME}:${BUILDING_BLOCK_TOKEN}@${BUILDING_BLOCK_REPO_URL}" \
        "../${BUILDING_BLOCK_FOLDER}"

      if [ ! -d "../${BUILDING_BLOCK_FOLDER}" ]; then
        echo "BuildingBlock repository clone failed!"
        exit 1
      fi

      echo "@@@@@@@@@@@@@@ Preparing BuildingBlock Repo Finished at: $(date '+%X') @@@@@@@@@@@@@@"

    - docker rmi "${IMAGE_NAME}:${IMAGE_TAG}${BACKUP_SUFFIX}" || echo "Old backup image does not exist"

    - |
      if docker image inspect "${IMAGE_NAME}:${IMAGE_TAG}" > /dev/null 2>&1; then
        docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_NAME}:${IMAGE_TAG}${BACKUP_SUFFIX}"
        echo "Backup image created"
      else
        echo "No existing image found, skipping backup"
      fi

    - docker compose build --no-cache

.deploy-template:
  stage: deploy
  script:
    - docker compose -p "${PROJECT_NAME}" down || true
    - docker compose -p "${PROJECT_NAME}" up -d

.cleanup-template:
  stage: cleanup
  script:
    - |
      set -e

      df -h --total

      THRESHOLD_PERCENT=80
      DISK_USED_PERCENT=$(df / --output=pcent | tail -1 | tr -d ' %')

      echo "Disk usage: ${DISK_USED_PERCENT}%"

      if [ "$DISK_USED_PERCENT" -ge "$THRESHOLD_PERCENT" ]; then
        echo "High disk usage detected. Running docker system prune..."
        docker system prune -f || true
      else
        echo "Disk usage is normal. Skipping cleanup."
      fi

.stage-environment:
  only:
    - stage
  variables:
    IMAGE_TAG: "stage"
    ENVIRONMENT: "Development"
    PORT_NUM_EXPOSED: 44381

.prod-environment:
  only:
    - main
  variables:
    IMAGE_TAG: "prod"
    ENVIRONMENT: "Production"
    PORT_NUM_EXPOSED: 44381

build-stage:
  extends:
    - .build-template
    - .stage-environment

deploy-stage:
  extends:
    - .deploy-template
    - .stage-environment

cleanup-stage:
  extends:
    - .cleanup-template
    - .stage-environment

build-prod:
  extends:
    - .build-template
    - .prod-environment

deploy-prod:
  extends:
    - .deploy-template
    - .prod-environment

cleanup-prod:
  extends:
    - .cleanup-template
    - .prod-environment